VIDSOL-418 ensure instance url is not empty when notify to slack

diff --git a/.github/actions/deploy-vcr/action.yml b/.github/actions/deploy-vcr/action.yml
--- a/.github/actions/deploy-vcr/action.yml
+++ b/.github/actions/deploy-vcr/action.yml
@@ -50,4 +50,8 @@ runs:
         fi
 
         INSTANCE_URL=$(grep -oE 'https://[^ ]+' deploy-vcr-logs.log | tail -1 | sed -r 's/\x1B\[[0-9;]*[mK]//g')
-        echo "instance_url=${INSTANCE_URL:-}" >> "$GITHUB_OUTPUT"
+        if [ -z "$INSTANCE_URL" ]; then
+          echo "Failed to extract instance URL from deploy logs"
+          exit 1
+        fi
+        echo "instance_url=${INSTANCE_URL}" >> "$GITHUB_OUTPUT"
